# Rotation matrix demo

Rotation matrix is defined by coordinates of new axes orts $[e_x', e_y', e_z']$, which present coordinates of the new orts in the original one: $[e_x, e_y, e_z]$.
Rotation of a given vector $v=[v_x,v_y, v_z]$ in original coordinates, means linear combination of $v_x \cdot e_x' + v_y \cdot e_y' + v_z \cdot e_z' $.

The new orts form columns of the rotation matix in C-format for usuage in numpy-like code.

MCNP uses Fortran presentation in the transformation specs. 

So, for the MCNP specification the transformation matrix should be saved as transposed, and transposed back on reading.


In [21]:
import numpy as np

In [22]:
from mckit import Transformation

In [23]:
def calc_z_rotation(theta: float):
    return np.array(
        [
            [np.cos(theta), -np.sin(theta), 0],
            [np.sin(theta), np.cos(theta), 0],
            [0,             0,             1],
        ],
        dtype=np.float64
    )

In [24]:
r4 = calc_z_rotation(np.pi/4)
r4

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [25]:
r4 @ [-1, -1, 0]

array([-1.11022302e-16, -1.41421356e+00,  0.00000000e+00])

In [29]:
tr = Transformation(rotation=r4)

In [30]:
tr.apply2point([1, 0, 0])

array([0.70710678, 0.70710678, 0.        ])

In [31]:
np.array(tr.get_words()).reshape((4,6))

array([[' ', '0', ' ', '0', ' ', '0'],
       [' ', '45', ' ', '45', ' ', '90'],
       [' ', '135', ' ', '45', ' ', '90'],
       [' ', '90', ' ', '90', ' ', '0']], dtype='<U3')