In [2]:
import numpy as np

In [3]:
from mckit import Transformation

In [4]:
def calc_z_rotation(theta: float):
    return np.array(
        [
            [np.cos(theta), -np.sin(theta), 0],
            [np.sin(theta), np.cos(theta), 0],
            [0,             0,             1],
        ],
        dtype=np.float64
    )

In [5]:
r4 = calc_z_rotation(np.pi/4)
r4

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [6]:
r4 @ [1, 0, 0]

array([0.70710678, 0.70710678, 0.        ])

In [7]:
tr = Transformation(rotation=r4)

In [8]:
tr.apply2point([1, 0, 0])

array([0.70710678, 0.70710678, 0.        ])

In [9]:
np.array(tr.get_words()).reshape((4,6))

array([[' ', '0', ' ', '0', ' ', '0'],
       [' ', '45', ' ', '45', ' ', '90'],
       [' ', '135', ' ', '45', ' ', '90'],
       [' ', '90', ' ', '90', ' ', '0']], dtype='<U3')

In [10]:
180*(9/8)

202.5

In [17]:
r15 = calc_z_rotation((17/16)*np.pi)
r15

array([[-0.98078528,  0.19509032,  0.        ],
       [-0.19509032, -0.98078528,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [18]:
r15 @ [1, 0, 0]

array([-0.98078528, -0.19509032,  0.        ])

In [19]:
tr15 = Transformation(rotation=r15)

In [20]:
tr15.apply2point([1,0,0])

array([-0.98078528, -0.19509032,  0.        ])

In [21]:
np.array(tr15.get_words()).reshape((4,6))

array([[' ', '0', ' ', '0', ' ', '0'],
       [' ', '168.75', ' ', '101.25', ' ', '90'],
       [' ', '78.75', ' ', '168.75', ' ', '90'],
       [' ', '90', ' ', '90', ' ', '0']], dtype='<U6')